### PR TITLE
Support of inline CSS background images in HTML

### PR DESCRIPTION
**Pull request by evanderson**
- Added tests and functionality for inline CSS background images in the HTML
- Also opened SVGs up to be CDN'ed as well

### CODE REVIEW

**Comment by twinfred** [comment]
This is definitely needed!

**Review by twinfred — APPROVED** [review]

**Review by lahela3 — APPROVED** [review]

**Review by ecjaffe — APPROVED** [review]
This is a great improvement!

**Review by gillesruppert — CHANGES_REQUESTED** [review]
Didn't run the tests but changes look good. Just one request: please add tests for the SVG addition as well please.

**Comment by evanderson** [comment]
No problem, I also opened the tests up to check each allowed image file type for the background images as well.

**Comment by evanderson** [comment]
Merge perhaps?

**Comment by gillesruppert** [comment]
Merged and published as new version on npm. Thanks for contributing and your patience.

**Pull request merged**
